on:
  push:

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run sh
        run: |
          sh blend.sh
          sudo apt-get install -y -q golang-go
          sudo go run render.go
          sh make.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate PNG"
          git pull 
          git push
